### ISSUE TITLE
Unknown package 'phantap'.

### ISSUE THREAD

**Issue by ju5tj05h** [nccgroup/phantap#5]
root@GL-AR150:~/phantap-master# opkg install phantap phantap-learn
Unknown package 'phantap'.
Unknown package 'phantap-learn'.
Collected errors:
 * opkg_install_cmd: Cannot install package phantap.
 * opkg_install_cmd: Cannot install package phantap-learn.

I copied the files over to the GL-AR150 but I'm unable to install the package. What would the steps leading up to "opkg install phantap phantap-learn" be? Do the files need to be uploaded to certain directories? Thanks.

**Comment by Bloup1net** [comment]
Hi @joshuamcvay ,

The phantap packages are only available in the master branch, the snapshot images. 
This is the setup process I just tested on one of my GL-AR150 routers:

- install the `https://downloads.openwrt.org/snapshots/targets/ath79/generic/openwrt-ath79-generic-glinet_gl-ar150-squashfs-sysupgrade.bin` image (without keeping any settings)

- after the device reboots and you connect your machine to the lan port and internet to the wan for example, pull the OpenWrt package list
```
# opkg update
```

- install the luci web interface and phantap packages
```
# opkg install luci-openssl phantap phantap-learn
``` 

Thanks for using phantap and don't hesitate to report any other issues.

**Comment by ridiadam** [comment]
Hi, 

is there a snapshot image for the GL-MV1000W that will allow me to install phantap ?
