### ISSUE TITLE
No internet access on PhanTap device

### ISSUE THREAD

**Issue by ju5tj05h** [nccgroup/phantap#7]
I have PhanTap in place between my victim machine and their switch. I am able to connect to PhanTap over WLAN and I am able to SSH to 192.168.1.1. I can run tcpdump and see traffic, but I don't seem to be able to access the internet from the PhanTap SSH session.
```
root@OpenWrt:~# uci show network
network.loopback=interface
network.loopback.ifname='lo'
network.loopback.proto='static'
network.loopback.ipaddr='127.0.0.1'
network.loopback.netmask='255.0.0.0'
network.globals=globals
network.globals.ula_prefix='fd65:9c67:dad1::/48'
network.lan=interface
network.lan.type='bridge'
network.lan.proto='static'
network.lan.ipaddr='192.168.1.1'
network.lan.netmask='255.255.255.0'
network.lan.ip6assign='60'
network.wan=interface
network.wan.proto='dhcp'
network.wan6=interface
network.wan6.proto='dhcpv6'
network.phantap=interface
network.phantap.type='bridge'
network.phantap.proto='static'
network.phantap.ipaddr='169.254.66.100'
network.phantap.netmask='255.255.255.254'
network.phantap.gateway='169.254.66.101'
network.phantap.ipv6='0'
network.phantap.ifname='eth0 eth1'
```

**Comment by champtar** [comment]
Hi @joshuamcvay 

Can you share the result of
```
logread | grep phantap
ip a
```
What device you are using ?
Maybe there is only IPv6 traffic ?

**Comment by ju5tj05h** [comment]
I'm using a GL-AR150. I can see the IPv4 traffic of the victim, but unable to access internet addresses from the PhanTap device.

logread | grep phantap produces several lines of…

Mon Aug  5 18:20:36 2019 daemon.info phantap-learn[1365]: Unknown ethertype 33024

ip a produces the following output...

1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel master br-phantap state UP group default qlen 1000
    link/ether e4:95:6e:48:c7:2b brd ff:ff:ff:ff:ff:ff
3: eth1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel master br-phantap state UP group default qlen 1000
    link/ether e4:95:6e:48:c7:2b brd ff:ff:ff:ff:ff:ff
5: br-phantap: <BROADCAST,NOARP,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether e4:95:6e:48:c7:2b brd ff:ff:ff:ff:ff:ff
    inet 169.254.66.100/31 brd 255.255.255.255 scope global br-phantap
       valid_lft forever preferred_lft forever
6: br-lan: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether e4:95:6e:48:c7:2b brd ff:ff:ff:ff:ff:ff
    inet 192.168.1.1/24 brd 192.168.1.255 scope global br-lan
       valid_lft forever preferred_lft forever
    inet6 fd65:9c67:dad1::1/60 scope global noprefixroute
       valid_lft forever preferred_lft forever
    inet6 fe80::e695:6eff:fe48:c72b/64 scope link
       valid_lft forever preferred_lft forever
7: wlan0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master br-lan state UP group default qlen 1000
    link/ether e4:95:6e:48:c7:2b brd ff:ff:ff:ff:ff:ff
    inet6 fe80::e695:6eff:fe48:c72b/64 scope link
       valid_lft forever preferred_lft forever

**Comment by champtar** [comment]
Interesting:
Unknown ethertype 33024 == Unknown ethertype 0x8100 (fixed in 9849b0f516238955f2b949337858822be485272c)
This is 802.1Q traffic (ie VLANs / https://en.wikipedia.org/wiki/IEEE_802.1Q)
Can you run tcpdump with `-e` to confirm and tell me if by any chance this is VLAN 0?
Also I'm curious, are you connected to a regular computer? can you give more information about your test environment (switch brand / ...)?
(I need to improve the BPF filter, we should not capture 802.1Q traffic)

**Comment by ju5tj05h** [comment]
I completely forgot about VLANs. I was able to connect to internet addresses on a non-vlan victim machine. I believe that port is actually tagged with 2 VLANs, Data and Voice (SIP). The switching is a mixture of Force10 and Nexus. I don't have the PhanTap hooked up to the same victim machine at the moment, but would be happy to provide more data tomorrow.

**Comment by champtar** [comment]
@joshuamcvay I just pushed a new version to OpenWrt, it should be built in the next 24h, If you can try it on the network with mixed vlans tell me if it work

**Comment by ju5tj05h** [comment]
@champtar, working beautifully! I was also able to get USB Tethering (GL-AR150+Android Phone) working. Gives me lots of ideas! Thanks again!

**Comment by champtar** [comment]
@joshuamcvay great to hear
