### ISSUE TITLE
ip-full error

### ISSUE THREAD

**Issue by burntbinnil** [nccgroup/phantap#8]
Managed to install phantap fine last week, but tried today a couple times and it keeps coming back with:

Collected errors:
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for phantap:
 * 	ip-full
 * opkg_install_cmd: Cannot install package phantap.
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for phantap-learn:
 * 	ip-full
 * opkg_install_cmd: Cannot install package phantap-learn.

on an AR-150 using snapshot firmaware you've linked.  Any ideas?

**Comment by burntbinnil** [comment]
Fixed, ip-full has failed to compile on the last snapshot so just used:

```
wget http://downloads.openwrt.org/releases/packages-18.06/mips_24kc/base/ip-full_4.16.0-8_mips_24kc.ipk

opkg install ip-full_4.16.0-8_mips_24kc.ipk
```

Fixed the error and allowed phantap to install.

**Comment by champtar** [comment]
ip-full seems to be present right now for master
https://downloads.openwrt.org/snapshots/packages/mips_24kc/base/
for OpenWrt related errors I would recommend IRC #openwrt on freenode
