### ISSUE TITLE
"Unknown package 'phantap-learn'" error during installation

### ISSUE THREAD

**Issue by cyb3rwr3ck** [nccgroup/phantap#9]
Hi there,
I am trying to install phantab as documented on a GL-AR150 but I am receiving the following error regarding the phantab-learn package while running _opkg install phantap phantap-learn_ on the latest snapshot-build (https://downloads.openwrt.org/snapshots/targets/ath79/generic/openwrt-ath79-generic-glinet_gl-ar150-squashfs-sysupgrade.bin).

```
[...]
Unknown package 'phantap-learn'.
Configuring kmod-ebtables.
Configuring ebtables.
Configuring libpcap1.
Configuring zlib.
Configuring libelf1.
Configuring libmnl0.
Configuring libcap.
Configuring ip-full.
Configuring kmod-br-netfilter.
Configuring kmod-ebtables-ipv4.
Configuring phantap.
Collected errors:
 * opkg_install_cmd: Cannot install package phantap-learn.
[...]
```

**Comment by champtar** [comment]
Hi @cyb3rwr3ck,

README is not up to date, everything is in `phantap` package now and `phantap-learn` doesn't exist anymore

**Comment by cyb3rwr3ck** [comment]
Thx, it is working
